giantswarm/starboard-exporter

CHANGELOG.md
helm/starboard-exporter/Chart.yaml
helm/starboard-exporter/templates/servicemonitor.yaml
helm/starboard-exporter/values.yaml

Add ServiceMonitor

---

CHANGELOG.md
README.md
controllers/vulnerabilityreport_controller.go
controllers/vulnerabilityreport_metrics.go
helm/starboard-exporter/Chart.yaml
helm/starboard-exporter/templates/grafana-dashboard.yaml
helm/starboard-exporter/templates/rbac.yaml
helm/starboard-exporter/templates/servicemonitor.yaml
helm/starboard-exporter/values.yaml
main.go

Support configurable target labels

---

CHANGELOG.md
README.md
controllers/vulnerabilityreport_controller.go
controllers/vulnerabilityreport_metrics.go
helm/starboard-exporter/templates/deployment.yaml
helm/starboard-exporter/values.yaml
main.go

Configure target labels via values file

---

.circleci/config.yml

Re-enable push to aliyun

---

.circleci/config.yml
CHANGELOG.md
helm/starboard-exporter/templates/grafana-dashboard.yaml

Add push to AWS and Azure collections

---

CHANGELOG.md
helm/starboard-exporter/templates/deployment.yaml
helm/starboard-exporter/values.yaml

Make resources configurable

---

README.md

This is a feature that many users of this exporter will want to use.
Fixes: #35

[docs] Enable one vuln report rs per deployment

---

CHANGELOG.md

Update Changelog for v0.2.1 release

---

CHANGELOG.md
helm/starboard-exporter/templates/deployment.yaml

- Add NodeAffinity to run it only on Linux Nodes with AMD64 Arch.
- Update CHANGELOG.md
Update Changelog

Add NodeAffinity

---

.abs/main.yaml
.circleci/config.yml
.github/pull_request_template.md
CHANGELOG.md
helm/starboard-exporter/Chart.yaml

Use `abs` for building project

---

helm/starboard-exporter/templates/deployment.yaml
helm/starboard-exporter/values.yaml

Add nodeSelector Helm value

---

CHANGELOG.md
controllers/configauditreport/configauditreport_controller.go
controllers/key.go
controllers/vulnerabilityreport/vulnerabilityreport_controller.go
controllers/vulnerabilityreport/vulnerabilityreport_metrics.go
controllers/vulnerabilityreport_controller.go
helm/starboard-exporter/templates/deployment.yaml
helm/starboard-exporter/values.yaml
main.go
utils/jitter.go

Spread re-queued reports over a configurable interval

---

CHANGELOG.md
README.md

Update docs for 0.5.0 release

---

CHANGELOG.md
helm/starboard-exporter/templates/deployment.yaml
helm/starboard-exporter/values.yaml

Add replicas value

---

CHANGELOG.md
helm/starboard-exporter/templates/deployment.yaml
helm/starboard-exporter/values.yaml

Helm:
Adding option to configure tolerations when selected nodes have taints

Add configurable tolerations in helm

---

helm/starboard-exporter/templates/deployment.yaml
helm/starboard-exporter/values.yaml

Makes starboard-exporter compliant with PSS restricted policies

Refactor security context for pod and container

---

CHANGELOG.md
helm/starboard-exporter/templates/servicemonitor.yaml

Make interval and scrapeTimeout configurable in helm chart

---

CHANGELOG.md
helm/starboard-exporter/templates/deployment.yaml
helm/starboard-exporter/values.yaml

Closes #140 
Unfortunately, I can't access the https://intranet.giantswarm.io/docs/organizational-structure/teams/cabbage/app-updates/helm-values-schema/ page without allowing certain permissions, so I'm not sure about the `values.schema.json` file.

feat: allow configuration of custom pod labels

---

CHANGELOG.md
go.mod
go.sum

Bump x/net dependency

---

.abs/main.yaml
.circleci/config.yml
CHANGELOG.md
helm/starboard-exporter/Chart.yaml
helm/starboard-exporter/templates/_helpers.tpl
helm/starboard-exporter/templates/deployment.yaml
helm/starboard-exporter/values.schema.json
helm/starboard-exporter/values.yaml

Build with `abs`

---

.ats/main.yaml
.circleci/config.yml
CHANGELOG.md
tests/ats/Pipfile
tests/ats/Pipfile.lock
tests/ats/test_basic_cluster.py

Add ATS tests

---

helm/starboard-exporter/values.schema.json

Change values schema validation to array for target labels

---

CHANGELOG.md
helm/starboard-exporter/values.schema.json
helm/starboard-exporter/values.yaml

tolerations is an array

---

.nancy-ignore
CHANGELOG.md
README.md
docs/custom_metrics_hpa.md
helm/starboard-exporter/templates/customMetricsHpa.yaml
helm/starboard-exporter/values.schema.json
helm/starboard-exporter/values.yaml

Signed-off-by: Rewanth Tammana <22347290+rewanthtammana@users.noreply.github.com>
Closes https://github.com/giantswarm/giantswarm/issues/24377

Add Horizontal Pod Autoscaling based on Prometheus scrape times

---

CHANGELOG.md
Dockerfile

This was mostly to test a CI change

Bump Go version

---

helm/starboard-exporter/templates/deployment.yaml
helm/starboard-exporter/values.yaml

Add imagePullSecrets to chart

---

CHANGELOG.md
helm/starboard-exporter/values.schema.json

From https://github.com/giantswarm/starboard-exporter/pull/179
- Update values schema
- Update CHANGELOG

Update changelog and values schema

---

helm/starboard-exporter/templates/rbac.yaml

fix namespace for RoleBinding

---

CHANGELOG.md

Changelog from #194

---

CHANGELOG.md
helm/starboard-exporter/templates/scaledobject.yaml
helm/starboard-exporter/values.schema.json
helm/starboard-exporter/values.yaml

Adds support for KEDA by adding a ScaledObject CR

Add scaledObject for KEDA support

---

.github/workflows/test-scorecard.yml

Test OSSF scorecard action

---

.github/workflows/zz_generated.run_ossf_scorecard.yaml

Towards https://github.com/giantswarm/giantswarm/issues/24297
Tests https://github.com/giantswarm/devctl/pull/750

Test OSSF workflow from devctl

---

.github/workflows/zz_generated.check_values_schema.yaml
.github/workflows/zz_generated.create_release.yaml
.github/workflows/zz_generated.create_release_pr.yaml
.github/workflows/zz_generated.gitleaks.yaml
.github/workflows/zz_generated.run_ossf_scorecard.yaml

Test OSSF bumps

---

README.md

Add OSSF badge

---

CHANGELOG.md
helm/starboard-exporter/templates/customMetricsHpa.yaml

Fix HPA API version.

---

.nancy-ignore
CHANGELOG.md
go.mod

Bump go to 1.22

---

.nancy-ignore
go.mod
go.sum

Fix Nancy reported vulnerabilities

Fix vulnerabilities

---

CHANGELOG.md
helm/starboard-exporter/templates/vpa.yaml
helm/starboard-exporter/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/31558

Add VPA config

---

.nancy-ignore

Run nancy-fixer

---

tests/ats/Pipfile

Unpin ats python minor version

---

.circleci/config.yml
Dockerfile

Some minor clean up of things I noticed in the previous release
- Dockerfile syntax: align FROM.. AS capitalization
- Remove azure collection push (all azure customers use capz now)
- Simplify aws collection push rules
- Clean up wonky whitespace in CircleCI config

Some build process housekeeping

---

CHANGELOG.md
helm/starboard-exporter/templates/deployment.yaml
helm/starboard-exporter/values.schema.json
helm/starboard-exporter/values.yaml

Fix imagePullSecrets
